### PR TITLE
Generating a graph as big as needed

### PR DESCRIPTION
**Pull request by fkarg**
Should work, the randomGraph function can easily be used I guess.
The number of Nodes within the Graph is the only parameter of it, it is IO because it is at least somewhat random (or is at least supposed to be so).
something else: the number of generated Ticks is hardcoded, but can be changed as needed. 
So is the Edge-generation, and how they are being connected, this might as well be changed in the future.

Closing #20

### CODE REVIEW

**Comment by sternenseemann** [comment]
Is `matchTriple` needed? I suppose not.

**Comment by sternenseemann** [comment]
Please do not merge yet; I possibly got something nice in the pipeline.

**Comment by fkarg** [comment]
You're right, it implies it since it's unused, but it actually is a way more performant function to remove the duplicates. will fix this now

**Comment by sternenseemann** [comment]
We should be done here now. :+1: :new_moon_with_face:

**Comment by froozen** [comment]
I'll give my approval as well. :+1:

**Pull request merged**
